version: '3.8'
services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb-partition
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: partitiondb
    ports:
      - "3306:3306"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
